language: java

script:
- ./gradlew --refresh-dependencies
- mkdir dist/libs/s3
- mv dist/libs/runwar* dist/libs/s3
- cd dist/libs/s3
- for file in *.jar; do fname=$(echo ${file%.jar} | sed 's/runwar-//'); mkdir -- "${fname}"; mv -- "$file" ${fname}; done


deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - master
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: dist/libs/s3
    upload-dir: cfmlprojects/runwar
    acl: public_read
