language: java

script:
- ./gradlew --refresh-dependencies
- mkdir dist/libs/s3
- mv dist/libs/runwar-4.0.0-SNAPSHOT.jar dist/libs/s3/runwar-4.0.0-SNAPSHOT.jar

deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - develop
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: dist/libs/s3
    upload-dir: cfmlprojects/runwar/$version
    acl: public_read