language: java

script:
- ./gradlew --refresh-dependencies

deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - develop
    skip_cleanup: false
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: dist/libs/runwar-4.0.0-SNAPSHOT.jar
    upload-dir: cfmlprojects/runwar/$version
    acl: public_read